// Generated by Wrangler by running `wrangler types`

interface Env {
  PLUGIN_PARENT_DOMAIN: "plugins.framercdn.com";
  PLUGIN_ID: string;
  CLIENT_ID: string;
  CLIENT_SECRET: string;
  REDIRECT_URI: string;
  AUTHORIZE_ENDPOINT: string;
  TOKEN_ENDPOINT: string;
  SCOPE: string;
  DB: D1Database;
}
