// Generated by Wrangler on Thu Oct 10 2024 14:20:35 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
  keyValueStore: KVNamespace
  PLUGIN_PARENT_DOMAIN: "plugins.framercdn.com"
  CLIENT_ID: string
  CLIENT_SECRET: string
  PLUGIN_ID: string
  REDIRECT_URI: string
  AUTHORIZE_ENDPOINT: string
  TOKEN_ENDPOINT: string
  SCOPE: string
}
