// Generated by Wrangler on Wed May 29 2024 11:22:07 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
	keyValueStore: KVNamespace;
	CLIENT_ID: string;
	CLIENT_SECRET: string;
	PLUGIN_URI: string;
	REDIRECT_URI: string;
	AUTHORIZE_ENDPOINT: string;
	TOKEN_ENDPOINT: string;
	SCOPE: string;
}
