#:schema node_modules/wrangler/config-schema.json
name = "framer-plugin-oauth"
main = "src/index.ts"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

[vars]
PLUGIN_PARENT_DOMAIN = "plugins.framercdn.com"
